### ISSUE TITLE
Game Crash - Storage Trailer

### ISSUE THREAD

**Issue by CheekierSky** [MrCrayfish/MrCrayfishVehicleMod#183]
I am running a Forge Minecraft Server ( version 30.0.39- 1.15.1) After installing the vehicle mod and Obfuscate (Both 1.15.2 because it mentioned working on 1.15.1 and we couldn't get 1.15.1 to work correctly about a week ago) our games would crash after looking at the storage trailer in the workbench or even looking at the storage trailer crate after putting it in our inventory.  If looking at the crate it would cause perpetual crashes upon trying to load into the game. 

Here is my crash log:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 1/23/20 5:04 PM
Description: Rendering entity in world

java.lang.NoSuchMethodError: net.minecraft.item.Item.getItemStackTileEntityRenderer()Lnet/minecraft/client/renderer/tileentity/ItemStackTileEntityRenderer;
	at com.mrcrayfish.vehicle.util.RenderUtil.renderModel(RenderUtil.java:138) ~[?:0.42.4-1.15.2] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:52) ~[?:0.42.4-1.15.2] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:21) ~[?:0.42.4-1.15.2] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.RenderVehicleWrapper.render(RenderVehicleWrapper.java:68) ~[?:0.42.4-1.15.2] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.render(RenderEntityVehicle.java:46) ~[?:0.42.4-1.15.2] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:17) ~[?:0.42.4-1.15.2] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:245) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1094) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:948) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:controllable:screen_render_patch,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:423) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:controllable:screen_render_patch,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:882) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:controllable:minecraft,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:520) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:controllable:minecraft,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:202) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.1-30.0.39.jar:30.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$401/1147394515.call(Unknown Source) [forge-1.15.1-30.0.39.jar:30.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mrcrayfish.vehicle.util.RenderUtil.renderModel(RenderUtil.java:138)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:52)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:21)
	at com.mrcrayfish.vehicle.client.render.RenderVehicleWrapper.render(RenderVehicleWrapper.java:68)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.render(RenderEntityVehicle.java:46)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:17)

-- Entity being rendered --
Details:
	Entity Type: vehicle:storage_trailer (com.mrcrayfish.vehicle.entity.trailer.StorageTrailerEntity)
	Entity ID: 18294
	Entity Name: Storage Trailer
	Entity's Exact location: -888.50, 68.00, 836.50
	Entity's Block location: World: (-889,68,836), Chunk: (at 7,4,4 in -56,52; contains blocks -896,0,832 to -881,255,847), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Entity's Momentum: 0.00, -0.80, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: com.mrcrayfish.vehicle.client.render.RenderEntityVehicle@cf825e8
	Location: -1.10,-1.62,-1.93 - World: (-2,-2,-2), Chunk: (at 14,-1,14 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: 0.0
	Delta: 0.34000015
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:245)
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1094)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:948)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['CheekierSky45'/18292, l='MpServer', x=-887.40, y=68.00, z=838.43]]
	Chunk stats: Client Chunk Cache: 1521, 263
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -1836236937846370886
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10 game time, 10 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1698)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:534)
	at net.minecraft.client.main.Main.main(SourceFile:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$401/1147394515.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.1
	Minecraft Version ID: 1.15.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 655814160 bytes (625 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.1-30.0.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.1-30.0.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.39.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.1-30.0.39.jar fml TRANSFORMATIONSERVICE 
	FML: 30.0
	Forge: net.minecraftforge:30.0.39
	FML Language Providers: 
		javafml@30.0
		minecraft@1
	Mod List: 
		forge-1.15.1-30.0.39-client.jar Minecraft {minecraft@1.15.1 DONE}
		FallingTree-1.15.1-2.0.2+13.jar Falling Tree {falling_tree@2.0.2+13 DONE}
		obfuscate-0.3.4-1.15.2.jar Obfuscate {obfuscate@0.3.4 DONE}
		forge-1.15.1-30.0.39-universal.jar Forge {forge@30.0.39 DONE}
		controllable-0.7.1-mc1.15.jar Controllable {controllable@0.7.1 DONE}
		Xaeros_Minimap_1.19.7_Forge_1.15.1.jar Xaero's Minimap {xaerominimap@1.19.7 DONE}
		valhelsia_structures-1.15.1-0.0.1.jar Valhelsia Structures {valhelsia_structures@1.15.1-0.0.1 DONE}
		nophantomnocry-1.15.1-1.0.jar NoPhantomNoCry {nophantomnocry@version DONE}
		nhacampfire_1.15-1.5.jar No Hostiles Around Campfire {nhacampfire@1.5 DONE}
		cfm-7.0.0-pre16-mc1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		corail_pillar-4.5.4-1.15.1.jar Corail Pillar {corail_pillar@4.5.4 DONE}
		vehicle-mod-0.42.4-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.42.4 DONE}
		sit-1.15.1-v1.3.jar Sit {sit@v1.3 DONE}
	Launched Version: 1.15.1-forge-30.0.39
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2080/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.42, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources (incompatible), vanilla
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz

**Comment by MrCrayfish** [comment]
I've updated the file to mention it will not work on 1.15.1. You will now have to download the 1.15.1 version for it to work.
