### ISSUE TITLE
[1.12.2] Crash on startup

### ISSUE THREAD

**Issue by MusicMaestro123** [MrCrayfish/MrCrayfishVehicleMod#271]
Just another crash: [Click for crash report and all will be explained!](https://pastebin.com/e6Eedcju)

**Comment by UnclassifiedX** [comment]
Testing 0.44.0 on 1.12.2 with obfuscate 0.4.2 works fine for me (asides from the gas issue at #270) there seems to be another mod that is causing the issue, what is the mod list?

**Comment by MusicMaestro123** [comment]
Check the crash report because who has time to write out 343 mods?

**Comment by MusicMaestro123** [comment]
Seems to work fine on 0.43.5 though.

**Comment by MrCrayfish** [comment]
If you don't have the time to write out 343 mods, who has the time to figure out which mod is causing the issue. I will tell you right now that nothing major changed in the new update, it's just another vehicle in the mod. The fact that it's saying `java.lang.NoClassDefFoundError` on the ATV is concerning and it's most likely caused by one of the 30 core mods you have installed. Also you should start playing the game on a more modern version of Minecraft, I won't be supporting 1.12.2 much longer. Please don't reply "but more people play on this version" or something along the lines.
